const activities = {
  "turtle-cove": { title:"Turtle Cove Reef Cruise",category:"Water adventure",location:"Nassau, The Bahamas",price:116,duration:"3.5 hours",rating:"4.90",reviews:"1,284 reviews",image:"https://images.unsplash.com/photo-1544550285-f813152fb2fd?auto=format&fit=crop&w=1400&q=85",gallery:["https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=82","https://images.unsplash.com/photo-1530053969600-caed2596d242?auto=format&fit=crop&w=800&q=82","https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=800&q=82"],description:"Cruise from Nassau to a protected reef where clear water, colorful fish and easy conditions make this a favorite for first-time and experienced snorkelers. Your local crew handles equipment, safety and island refreshments.",meeting:"Paradise Island Ferry Terminal, Dock B",includes:["Round-trip boat transfer","Snorkel mask, fins and vest","Local captain and guide","Bottled water and fruit","Reef safety briefing","Digital itinerary ticket"]},
  "nassau-city": { title:"Nassau Highlights Tour",category:"Tour & excursion",location:"Nassau, The Bahamas",price:59,duration:"2.5 hours",rating:"4.7",reviews:"84 reviews",image:"https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?auto=format&fit=crop&w=1400&q=85",gallery:["https://images.unsplash.com/photo-1526772662000-3f88f10405ff?auto=format&fit=crop&w=800&q=82","https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=800&q=82","assets/guide-hidden.png"],description:"See Nassau through the stories of a local host. Visit the Queen’s Staircase, historic forts, colorful downtown streets and the market, with time for a small tasting along the way.",meeting:"Rawson Square fountain, Downtown Nassau",includes:["Local guide","Small-group transport","Market tasting","Fort admission","Bottled water","Digital city map"]},
  "chef-table": { title:"Island Chef’s Table",category:"Food & dining",location:"Cable Beach, The Bahamas",price:85,duration:"2 hours",rating:"4.9",reviews:"61 reviews",image:"https://images.unsplash.com/photo-1563379926898-05f4575a45d8?auto=format&fit=crop&w=1400&q=85",gallery:["assets/guide-food.png","https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=82","https://images.unsplash.com/photo-1559847844-5315695dadae?auto=format&fit=crop&w=800&q=82"],description:"A relaxed multi-course tasting that celebrates Bahamian seafood, seasonal produce and family recipes. The chef introduces each plate while the group enjoys a reserved waterfront table.",meeting:"Cable Beach culinary studio entrance",includes:["Five tasting courses","Welcome drink","Chef introduction","Reserved waterfront table","Dietary substitutions","Recipe card"]},
  "ocean-spa": { title:"Oceanfront Spa Ritual",category:"Wellness & luxury",location:"Paradise Island, The Bahamas",price:160,duration:"90 minutes",rating:"4.8",reviews:"47 reviews",image:"https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1400&q=85",gallery:["https://images.unsplash.com/photo-1519823551278-64ac92734fb1?auto=format&fit=crop&w=800&q=82","https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?auto=format&fit=crop&w=800&q=82","https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&w=800&q=82"],description:"Reset between island adventures with a customized massage, mineral salt scrub and quiet ocean-terrace recovery time at a locally operated spa.",meeting:"Paradise Island spa reception",includes:["Personal consultation","60-minute massage","Mineral salt scrub","Ocean terrace access","Tea and refreshments","Robes and lockers"]}
};
Object.assign(activities, {
  "rose-island-sail": {title:"Private Golden-Hour Sail to Rose Island",category:"Private sailing experience",location:"Nassau, The Bahamas",price:185,duration:"4.5 hours",rating:"4.98",reviews:"184 reviews",image:"https://images.unsplash.com/photo-1544550285-f813152fb2fd?auto=format&fit=crop&w=1400&q=85",gallery:["https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=800&q=82","https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=82","https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=800&q=82"],description:"Leave Nassau Harbour as the afternoon cools for a private sail to Rose Island. Snorkel a quiet reef, relax on deck and watch the island turn gold over a locally prepared dinner.",meeting:"Nassau Yacht Haven, Private Charter Dock",includes:["Private sailboat and captain","Rose Island reef stop","Snorkeling equipment","Locally prepared dinner","Drinks and refreshments","Golden-hour photo package"]},
  "exuma-cays": {title:"Exuma Cays & Swimming Pigs",category:"Island adventure",location:"Exuma, The Bahamas",price:235,duration:"8 hours",rating:"4.98",reviews:"1,106 reviews",image:"assets/guide-water.png",gallery:["https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=82","https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=82","assets/guide-beach.png"],description:"Spend a full day crossing turquoise cays, swimming with Exuma’s famous pigs and snorkeling a calm reef with a small local crew.",meeting:"Nassau Harbour, East Dock",includes:["Round-trip speedboat","Swimming Pigs stop","Reef snorkeling gear","Island lunch","Drinks and snacks","Local captain and guide"]},
  "azure-day-pass": {title:"Azure Beach Club Day Pass",category:"Beach club",location:"Cable Beach, Nassau",price:89,duration:"Full day",rating:"4.86",reviews:"746 reviews",image:"assets/guide-beach.png",gallery:["https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=800&q=82","https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=82","assets/guide-water.png"],description:"Settle into a reserved lounger with pool and beach access, a welcome drink and lunch credit at Cable Beach’s relaxed oceanfront club.",meeting:"Azure Beach Club reception, Cable Beach",includes:["Reserved lounger","Pool and beach access","Welcome drink","Lunch credit","Towels","Changing facilities"]},
  "sunset-sail": {title:"Small-Group Sunset Sail",category:"Sailing",location:"Nassau Harbour",price:72,duration:"2.5 hours",rating:"4.91",reviews:"613 reviews",image:"https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1400&q=85",gallery:["https://images.unsplash.com/photo-1544550285-f813152fb2fd?auto=format&fit=crop&w=800&q=82","https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=800&q=82","https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=82"],description:"Sail beyond Nassau Harbour with a small group as the sky changes color, with light bites, chilled drinks and room to relax on deck.",meeting:"Nassau Yacht Haven, Gate 2",includes:["Sunset sailing cruise","Captain and crew","Welcome drink","Light bites","Safety equipment","Digital photos"]},
  "hidden-eleuthera": {title:"Hidden Eleuthera with a Local",category:"Guided island tour",location:"Eleuthera, The Bahamas",price:125,duration:"6 hours",rating:"4.88",reviews:"172 reviews",image:"assets/guide-hidden.png",gallery:["assets/guide-beach.png","https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?auto=format&fit=crop&w=800&q=82","https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=82"],description:"Follow a local host to quiet coves, roadside food stops and viewpoints that most day visitors miss on a flexible small-group route.",meeting:"Governor’s Harbour welcome centre",includes:["Local host","Air-conditioned transport","Beach stops","Local lunch tasting","Bottled water","Hotel-area pickup"]},
  "sunset-beach-session": {title:"Sunset Beach Session",category:"Beach experience",location:"Cable Beach, Nassau",price:32,duration:"2 hours",rating:"4.76",reviews:"284 reviews",image:"https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?auto=format&fit=crop&w=1400&q=85",gallery:["https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=82","assets/guide-beach.png","https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=800&q=82"],description:"Join a laid-back golden-hour beach gathering with music, a welcome drink and casual games before the sun drops over Cable Beach.",meeting:"Cable Beach public access pavilion",includes:["Reserved beach area","Welcome drink","Beach games","Local host","Sunset photo stop","Light snacks"]},
  "nassau-highlights": {title:"Nassau Highlights & Tastings",category:"Culture & food",location:"Downtown Nassau",price:50,duration:"3 hours",rating:"4.79",reviews:"932 reviews",image:"https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?auto=format&fit=crop&w=1400&q=85",gallery:["assets/guide-food.png","assets/guide-hidden.png","https://images.unsplash.com/photo-1526772662000-3f88f10405ff?auto=format&fit=crop&w=800&q=82"],description:"Walk through Nassau’s landmarks and colorful streets, stopping for small Bahamian tastings and stories from a local guide.",meeting:"Rawson Square fountain, Downtown Nassau",includes:["Local guide","Five tasting stops","Historic landmarks","Market visit","Bottled water","Digital neighborhood guide"]},
  "nassau-art-walk": {title:"Nassau Art Walk After Dark",category:"Arts & nightlife",location:"Downtown Nassau",price:25,duration:"2 hours",rating:"4.67",reviews:"196 reviews",image:"https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&w=1400&q=85",gallery:["https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?auto=format&fit=crop&w=800&q=82","https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=800&q=82","https://images.unsplash.com/photo-1561214115-f2f134cc4912?auto=format&fit=crop&w=800&q=82"],description:"Meet working artists, see murals after sunset and finish at a lively downtown gallery bar on this guided evening walk.",meeting:"Pompey Square arch, Downtown Nassau",includes:["Local arts guide","Gallery entry","Mural route","Welcome drink","Artist meet-and-greet","Digital art map"]},
  "exuma-sound-weekend": {title:"Exuma Sound Weekend",category:"Music & events",location:"George Town, Exuma",price:60,duration:"5 hours",rating:"4.82",reviews:"521 reviews",image:"https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?auto=format&fit=crop&w=1400&q=85",gallery:["https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&w=800&q=82","https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=800&q=82","https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=800&q=82"],description:"Spend Saturday by the water with Bahamian performers, island food vendors and a sunset headline set in George Town.",meeting:"Regatta Park main entrance, George Town",includes:["Event admission","Live performances","Reserved viewing area","Welcome drink","Vendor guide","Digital event pass"]}
});
const params = new URLSearchParams(location.search);
const id = activities[params.get("id")] ? params.get("id") : "turtle-cove";
const activity = activities[id];
const adultOnlyActivities = new Set(["chef-table", "ocean-spa", "sunset-beach-session", "nassau-art-walk", "exuma-sound-weekend"]);
activity.audience = adultOnlyActivities.has(id) ? "adult-only" : "all-ages";
document.title = `${activity.title} | Voyara`;
document.querySelector("#detail-title").textContent = activity.title;
document.querySelector("#detail-location").textContent = `${activity.location} · ${activity.category}`;
document.querySelector("#detail-rating").textContent = `★ ${activity.rating} · ${activity.reviews}`;
document.querySelector("#detail-description").textContent = activity.description;
document.querySelector("#detail-duration").textContent = activity.duration;
document.querySelector("#detail-meeting").textContent = activity.meeting;
document.querySelector("#detail-price").textContent = `$${activity.price}`;
document.querySelector("#gallery-main").src = activity.image;
activity.gallery.forEach((src,index)=>{document.querySelector(`#gallery-${index+2}`).src=src});
document.querySelector("#included-list").innerHTML = activity.includes.map(item=>`<li>${item}</li>`).join("");
const guestSelect = document.querySelector("#detail-guests");
const travelerLabel = guestSelect.closest("label");
const travelerCounts = { adults: 2, kids: 0 };
travelerLabel.innerHTML = `<span>Travelers</span>${activity.audience === "adult-only" ? '<small class="detail-age-notice">18+ experience · children are not permitted</small>' : ""}<div class="detail-traveler-picker">${[["adults","Adults","18+"],["kids","Kids","0–17"]].map(([key,label,ages])=>`<div class="detail-traveler-row${activity.audience === "adult-only" && key === "kids" ? " disabled" : ""}" data-detail-traveler="${key}"><span><b>${label}</b><small>${ages}</small></span><div><button type="button" data-detail-quantity="-1" aria-label="Remove ${label}">−</button><strong>0</strong><button type="button" data-detail-quantity="1" aria-label="Add ${label}">+</button></div></div>`).join("")}</div>`;
const renderTravelerCounts = () => travelerLabel.querySelectorAll("[data-detail-traveler]").forEach((row)=>{row.querySelector("strong").textContent=travelerCounts[row.dataset.detailTraveler]});
travelerLabel.querySelectorAll("[data-detail-quantity]").forEach((button)=>button.addEventListener("click",()=>{
  const row=button.closest("[data-detail-traveler]");
  if(row.classList.contains("disabled")) return;
  const key=row.dataset.detailTraveler;
  travelerCounts[key]=Math.max(key === "adults" ? 1 : 0,travelerCounts[key]+Number(button.dataset.detailQuantity));
  renderTravelerCounts();
}));
renderTravelerCounts();
const dateInput = document.querySelector("#detail-date");
const nextDay = new Date(); nextDay.setDate(nextDay.getDate()+1); dateInput.value = nextDay.toISOString().slice(0,10);
document.querySelector("#detail-book-form").addEventListener("submit",(event)=>{
  event.preventDefault();
  const guests = travelerCounts.adults + travelerCounts.kids;
  localStorage.setItem("voyara-booking-draft",JSON.stringify({id,...activity,date:dateInput.value,time:document.querySelector("#detail-time").value,travelers:{...travelerCounts},guests}));
  location.href="booking.html";
});
